version: 2

submodules:
  include: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true
